LTWebBanDT/Controllers/CartController.cs
using LTWebBanDT.Context;
using LTWebBanDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LTWebBanDT.Controllers
{
    public class CartController : Controller
    {
        LTWebBanHangEntities objLTWebBanHangEntities = new LTWebBanHangEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]); 
        }

        public ActionResult AddToCart(int id, int quantity) 
        {
            if (Session["cart"] == null) 
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objLTWebBanHangEntities.Products.Find(id), Quantity = quantity }); 
                Session["cart"] = cart; 
                Session["count"] = 1; 
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity += quantity;
                }
                else
                {
                    cart.Add(new CartModel { Product = objLTWebBanHangEntities.Products.Find(id), Quantity = quantity });
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.Id.Equals(id))
                    return i;
            return -1;
        }

        //Xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.Id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

LTWebBanDT/Controllers/PaymentController.cs
using LTWebBanDT.Context;
using LTWebBanDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace LTWebBanDT.Controllers
{
    public class PaymentController : Controller
    {
        LTWebBanHangEntities objLTWebBanHangEntities = new LTWebBanHangEntities();
        // GET: Payment
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home"); 
            }
            else
            {
                //Lấy thông tin từ giỏ hàng từ biến session
                var lstCart = (List<CartModel>)Session["cart"];
                //Gán dữ liệu cho bảng order
                Order objOrder = new Order();
                objOrder.Name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objOrder.UserId = int.Parse(Session["idUser"].ToString()); 
                objOrder.CreatedOnUtc = DateTime.Now;
                objOrder.Status = 1;
                objLTWebBanHangEntities.Orders.Add(objOrder);
                objLTWebBanHangEntities.SaveChanges();

                //Lấy OrderId vừa mới tạo để lưu vào bảng OrderDetail
                int intOrderId = objOrder.Id;

                List<OrderDetail> lstOrderDetail = new List<OrderDetail>(); 

                foreach (var item in lstCart) 
                {
                    OrderDetail obj = new OrderDetail();
                    obj.Quantity = item.Quantity;
                    obj.OrderId = intOrderId;
                    obj.ProductId = item.Product.Id;
                    lstOrderDetail.Add(obj);
                }
                objLTWebBanHangEntities.OrderDetails.AddRange(lstOrderDetail);
                objLTWebBanHangEntities.SaveChanges();
            }
            return View();
        }
    }
}

LTWebBanDT/Views/Cart/Index.cshtml
@model IEnumerable<LTWebBanDT.Models.CartModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //Lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data: JSON.stringify(model),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Sản phẩm</th>
                                <th scope="col" width="120">Số lượng</th>
                                <th scope="col" width="120">Giá tiền</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr id="product-@item.Product.Id">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.Avartar" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="~/Product/Detail/@item.Quantity" class="title text-dark">@item.Product.Name</a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <input type="text" value="@item.Quantity" />
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@item.Product.Price</var>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.Id" id="productid"/>
                                            <a href="" class="btn btn-light" id="removecart" > Xóa </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else 
                            {
                                <p>Không có sản phẩm trong giỏ hàng</p>
                            }

                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right"> Thanh toán <i class="fa fa-chevron-right"></i> </a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Tiếp tục mua sắm </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Miễn phí vận chuyển từ 1-2 tuần</p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Mã giảm giá</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Áp mã giảm giá vào đây">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Áp dụng</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card">
                    <div class="card-body">                     
                         <dl class="dlist-align">
                             <dt>Tổng tiền:</dt>
                             <dd class="text-right">7000000</dd>
                         </dl>
                         <p class="text-center mb-3">
                             <img src="~/Content/images/misc/payments.png" height="26">
                         </p>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>